tyson-swetnam:
  name: Tyson Lee Swetnam
  description: Author
  avatar: https://github.com/tyson-swetnam.png

openai:
  name: OpenAI
  description: Chat GPT-4 Editor
  avatar: https://github.com/openai.png